### ISSUE TITLE
[Python] [LGTM.com] False-positive: Unreachable statement

### ISSUE THREAD

**Issue by webknjaz** [Semmle/ql#2206]
**Description of the false positive**

In Python, context managers may suppress exceptions. And there's also a stdlib way of doing this which is `contextlib.suppress()` generator.

So
```python
import contextlib

def some_func():
    with contextlib.suppress(KeyError):
        return dict()['a_key']
    return 'fallback'
```
is not unreachable, it's basically the same as:
```python
def some_func():
    try:
        return dict()['a_key']
    except KeyError:
        return 'fallback'
```

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/ansible/ansible-lint/snapshot/5d850a33bfbeee2e45405e073f6c6117748b7673/files/lib/ansiblelint/versiontools.py?sort=name&dir=ASC&mode=heatmap#x513e4d26f9b3b6bd:1

**Comment by tausbn** [comment]
This was fixed in #2078, and should go live on LGTM.com in the coming weeks.

**Comment by tausbn** [comment]
The fix has now gone live, and the alert has gone away, so I'm closing this issue.

**Comment by webknjaz** [comment]
@tausbn I'm still seeing this: https://lgtm.com/projects/g/cherrypy/cheroot/snapshot/0c678bab518ca17151540b7d744faca49b941763/files/cheroot/ssl/builtin.py#x46e331ef60ba4bf1:1

**Comment by webknjaz** [comment]
Filed a new one for this: https://github.com/Semmle/ql/issues/2351.
