### ISSUE TITLE
LGTM.com - false positive for expression SFINAE with decltype

### ISSUE THREAD

**Issue by mavam** [Semmle/ql#2382]
Expression SFINAE in C++ produces false positives.

Here is a URL with a concrete example: https://lgtm.com/projects/g/tenzir/vast/snapshot/924daac2cb6f73a48d82e250f93035bced1c35d5/files/libvast/vast/concept/parseable/core/parser.hpp#x288490d9036c15a9:1

The code:
```cpp
template <class Iterator, class Attribute>
auto operator()(Iterator& f, const Iterator& l, Attribute& a) const
  -> decltype(*f, ++f, f == l, bool()) {
  ...
}
```

Anything code inside `decltype` is not executed and in this case only used to control the overload set of this function.

However, LGTM reports:

> This '==' operator has no effect. The assignment ('=') operator was probably intended.

This is wrong.

A possible solution would be to ignore anything inside `decltype`.

**Comment by jbj** [comment]
That's one creative use of `decltype`. I like it.

I'll look into what's the best way to suppress this alert and similar alerts in other queries.

**Comment by jbj** [comment]
I've opened #2391 with a proposed fix.

**Comment by mavam** [comment]
The fix seemsspecific to `operator==`, as opposed to all expressions in `decltype`. If it should only solve the confusion with assignment, then this works. But we have another set of FPs in other `decltype` expressions, e.g., a custom type trait via expression SFINAE:

https://lgtm.com/projects/g/tenzir/vast/snapshot/140ed574194024380fed5fdf5e5d115f038bd1a0/files/libvast/vast/concept/printable/core/printer.hpp#x51d07e96eb4b02c5:1

Personally, I don't see a use case for performing code analysis within `decltype`.

**Comment by jbj** [comment]
I've updated #2391 to add another exclusion that's specific to the "Expression has no effect" query. I agree that most of our analyses make no sense inside a `decltype` (or `sizeof` or other unevaluated context), but I don't think it will work to make such expressions invisible to all queries. That would lead to to false positives in queries of the type "this variable is never used".

**Comment by mavam** [comment]
Thanks for addressing the issue promptly. It's great to see responsive communication with the community! We can leave it like that for now. If there are other `decltype` issues coming up, I'll be flag them separately.

**Comment by jbj** [comment]
Thanks for the feedback.

Now that the fix has been merged, it should get deployed to lgtm.com in about two weeks from now.

**Comment by mavam** [comment]
@jbj just a quick question: has this fix been deployed yet? We still see the same FPs on your status page.

**Comment by jbj** [comment]
The deployment was supposed to have happened now, but some thorny performance issues with the Python analysis are blocking it. I hope we'll have the update deployed next week.

**Comment by mavam** [comment]
Thanks for the update and good luck with getting the performance regression under control!

**Comment by jbj** [comment]
The fix was deployed on 2019-12-19.
